modLoader = "javafml"
loaderVersion = "[31,)"

authors = "chylex"
license = "Unlicense"
issueTrackerURL = "https://github.com/chylex/Minecraft-Window-Title/issues"

[[mods]]
modId = "customwindowtitle"
version = "1.1.0"
displayName = "Custom Window Title"
displayURL = "https://github.com/chylex/Minecraft-Window-Title"

[[dependencies.customwindowtitle]]
modId = "minecraft"
mandatory = true
versionRange = "[1.15.2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.customwindowtitle]]
modId = "forge"
mandatory = true
versionRange = "[31,)"
ordering = "NONE"
side = "CLIENT"
