modLoader = "javafml"
loaderVersion = "[0,)"

license = "${license}"
issueTrackerURL = "${issuesURL}"

[[mods]]
modId = "${id}"
displayName = "${name}"
displayURL = "${sourcesURL}"
description = "${description}"
authors = "${author}"
version = "${version}"

[[mixins]]
config = "${id}.mixins.json"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minimumMinecraftVersion},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${id}]]
modId = "neoforge"
mandatory = true
versionRange = "[${minimumNeoForgeVersion},)"
ordering = "NONE"
side = "CLIENT"
